name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - languge-name: 'Polish'
            language-code: 'pl'
          - languge-name: 'English'
            language-code: 'en'
    steps:
      - name: test
        run: echo "Current laguage is ${{ matrix.language-name }} with code ${{ matrix.language-code }}"
